{
 "title": "MITF APM",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Requests Rate/Sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(calls_total[1m])) by(service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces Dashboard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(calls_total)", "legendFormat": "__auto" },
    {
     "expr": "sum(calls_total{status_code=\"STATUS_CODE_ERROR\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(calls_total{status_code=\"STATUS_CODE_UNSET\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jaeger_collector_traces_received_total) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Rate%",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(calls_total{status_code=\"STATUS_CODE_ERROR\"}) / sum(calls_total) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Latency Bucket (0.95 percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(latency_bucket{instance=\"localhost:8889\"}[1m])) by (service_name, le)) /1000   \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BV_MOBILE_INBOUND",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(MOBILE_CHANNEL{Path=\"BV_Transaction\",Status=\"IN_BOUND\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BV_MOBILE_REJECTED",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(MOBILE_CHANNEL{Path=\"BV_Transaction\",Status=\"REJECTED\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BV_DASHBOARD",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "sum(MOBILE_CHANNEL{Status=\"IN_BOUND\",Path=\"BV_Transaction\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(MITF_CORE{service=\"SYSTEM_CORE\",Status=\"SUCCESS\",Path=\"BuyVoucherArchiveConsumer\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(MOBILE_CHANNEL{Status=\"REJECTED\",Path=\"BV_Transaction\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(MTIF_CORE{Path=\"BuyVoucherArchiveConsumer\",Status=\"FAILED\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BV_CORE_SUCCESS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(MITF_CORE{service=\"SYSTEM_CORE\",Status=\"SUCCESS\",Path=\"BuyVoucherArchiveConsumer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BV_CORE_FAILED",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(MITF_CORE{service=\"SYSTEM_CORE\",Status=\"FAILED\",Path=\"BuyVoucherArchiveConsumer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MT_MOBILE_INBOUND",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(MOBILE_CHANNEL{Path=\"MT_Transaction\",Status=\"IN_BOUND\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MT_MOBILE_REJECTED",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(MOBILE_CHANNEL{Path=\"MT_Transaction\",Status=\"REJECTED\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MT_DASHBOARD",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "sum(MOBILE_CHANNEL{Status=\"IN_BOUND\",Path=\"MT_Transaction\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(MTIF_CORE{Path=\"MoneyTransferArchiveConsumer\",Status=\"SUCCESS\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(MOBILE_CHANNEL{Status=\"REJECTED\",Path=\"MT_Transaction\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(MTIF_CORE{Path=\"MoneyTransferArchiveConsumer\",Status=\"FAILED\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MT_CORE_SUCCESS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(MITF_CORE{service=\"SYSTEM_CORE\",Status=\"SUCCESS\",Path=\"MoneyTransferArchiveConsumer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BV_CORE_FAILED",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(MITF_CORE{service=\"SYSTEM_CORE\",Status=\"FAILED\",Path=\"MoneyTransferArchiveConsumer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ToChange: BV Latency in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(latency_bucket{operation=\"Core/BV\",service_name=\"TestingAPI\"}[1m])) by (service_name, le)) /1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}