{
 "title": "MITF STATISTICS DASHBOARD",
 "tags": [
  ".net",
  ".net core"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(http_requests_received_total, app)"
    }
   },
   {
    "name": "pods",
    "label": "pods",
    "query": {
     "query": "label_values(http_requests_received_total{app =~ \"$app\"}, kubernetes_pod_name)"
    }
   },
   {
    "name": "controllers",
    "label": "controllers",
    "query": {
     "query": "label_values(http_requests_received_total{app =~ \"$app\", kubernetes_pod_name=~ \"$pods\"}, controller)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU USAGE",
   "type": "stat",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_runtime_cpu_usage ", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (process_cpu_seconds_total{}[1m])) by (service)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{ }  /1024/1024 ",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{ }  /1024/1024 ",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_num_threads{} ", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_num_threads{} ", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  }
 ]
}