apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  orgId: 1
  url: http://host.docker.internal:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    httpMethod: GET

- name: Jaeger
  type: jaeger
  uid: jaeger-tracing
  access: proxy
  url: http://jaeger-query:16686/
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
      httpMethod: GET